name: FixedPowerups
main: mc.yqt.fixedpowerups.FixedPowerups
version: 1.0
author: yqt1001
depend: [ProtocolLib]
commands:
   powerup:
      description: Fixed powerup GUI
      usage: /<command>
      aliases: [powerups]