name: FixedPowerups
main: mc.yqt.fixedpowerups.FixedPowerups
version: 1.0
author: yqt1001
depend: [ProtocolLib]
commands:
   cps:
      description: Starts cps test
      usage: /<command>
      aliases: [cpstest, testcps]